version: '2.2'
services:
  memtiera:
    hostname: memtiera
    build: images/memtier_benchmark
    links:
      - redisa
      - influxdb
  redisa:
    image: redis:latest
  influxdb:
    image: influxdb:latest
  collector:
    build: images/collector
    command: [ "--influx", "--influxdbhost=influxdb" ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - influxdb
